CREATE TABLE IF NOT EXISTS thumbs (
    code SERIAL PRIMARY KEY,
    status VARCHAR(50),
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON TABLE thumbs TO homer;
GRANT ALL PRIVILEGES ON DATABASE homer_db TO homer;

GRANT USAGE, SELECT ON SEQUENCE thumbs_code_seq TO homer;
